outtur/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('web.cms.urls')),
    path('auth/', include('web.auth.urls')),
    path('profil/', include('web.profile.urls')),
    path('wydarzenia/', include('web.events.urls')),
    path('', include('web.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/events/urls.py
from django.urls import path

from web.events.views import EventDetails, EventMapView, EventsMapView, EventsView
from .views_ajax import add_user_to_event, ajax_filter_events, ajax_filter_events_map, add_like_event

app_name = "events"


urlpatterns = [
   path('add-user-to-event/<int:event_id>/', add_user_to_event, name='add_user_to_event'),
   path('add-like-event/<int:event_id>/', add_like_event, name='add_like_event'),
   path('ajax/filter-events/', ajax_filter_events, name='ajax_filter_events'),
   path('ajax/filter-events-map/', ajax_filter_events_map, name='ajax_filter_events_map'),
   
   path('<slug:slug>/<int:pk>/', EventDetails.as_view(), name='event_details'),
   path('<slug:slug>/mapa/<int:pk>/', EventMapView.as_view(), name='event_map'),
   path('mapa/', EventsMapView.as_view(), name='events_map'),
   path('lista/', EventsView.as_view(), name='events_list'),
]

web/models/events.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db.models import PointField
from django.dispatch import receiver
from multiselectfield import MultiSelectField
from django.utils.text import slugify

from web.constans import ADDED_BY_CHOICES, DAYS_OF_WEEK, ENTRY_CHOICES, EVENT_TYPE_CHOICES, LOCATION_CHOICES
from web.models.images import delete_thumbnails, make_thumbnail  


class Event(models.Model):
    # Informacje podstawowe o wydarzeniu
    name = models.CharField(
        max_length=140, 
        verbose_name="Nazwa wydarzenia",
        db_index=True
    )
    slug = models.SlugField(
        max_length=140, 
        verbose_name="Nazwa SEO",
        unique=True,
        blank=True,
        null=True
    )
    short_description = models.TextField(
        max_length=840, 
        verbose_name="Krótki opis wydarzenia"
    )
    description = models.TextField(
        blank=True, 
        null=True, 
        verbose_name="Opis wydarzenia"
    )
    city = models.CharField(
        max_length=255, 
        verbose_name="Miejscowość wydarzenia"
    )
    street = models.CharField(
        max_length=255, 
        verbose_name="Ulica wydarzenia"
    )
    house_number = models.CharField(
        max_length=255, 
        verbose_name="Numer domu wydarzenia",
        blank=True,
        null=True
    )
    postal_code = models.CharField(
        max_length=6, 
        verbose_name="Kod pocztowy wydarzenia",
        blank=True,
        null=True
    )
    apartment_number = models.CharField(
        max_length=255, 
        verbose_name="Numer lokalu wydarzenia",
        blank=True,
        null=True
    )

    # Obrazy
    main_image = models.ImageField(
        upload_to="events/main_images/", 
        verbose_name="Zdjęcie główne",
        blank=True,
        null=True
    )
    gallery_image_1 = models.ImageField(
        upload_to="media/events/gallery_images/", 
        verbose_name="Zdjęcie galerii 1",
        blank=True,
        null=True
    )
    gallery_image_2 = models.ImageField(
        upload_to="media/events/gallery_images/", 
        verbose_name="Zdjęcie galerii 2",
        blank=True,
        null=True
    )
    gallery_image_3 = models.ImageField(
        upload_to="media/events/gallery_images/", 
        verbose_name="Zdjęcie galerii 3",
        blank=True,
        null=True
    )
    gallery_image_4 = models.ImageField(
        upload_to="media/events/gallery_images/", 
        verbose_name="Zdjęcie galerii 4",
        blank=True,
        null=True
    )
    
    # Czas trwania wydarzenia
    event_type = models.CharField(
        max_length=20,
        choices=EVENT_TYPE_CHOICES,
        default="one_day",
        verbose_name="Rodzaj wydarzenia"
    )
    
    one_day_date = models.DateTimeField(
        blank=True, 
        null=True, 
        verbose_name="Data wydarzenia"
    )
    is_multi_day = models.BooleanField(
        default=False, 
        verbose_name="Kilku dniowe"
    )
    start_date = models.DateTimeField(
        blank=True, 
        null=True, 
        verbose_name="Data rozpoczęcia"
    )
    end_date = models.DateTimeField(
        blank=True, 
        null=True, 
        verbose_name="Data zakończenia"
    )

    # Wydarzenia cykliczne
    is_recurring = models.BooleanField(
        default=False, 
        verbose_name="Wydarzenie cykliczne"
    )
    day_of_week = MultiSelectField(
        choices=DAYS_OF_WEEK,
        blank=True,
        null=True,
        verbose_name="Dni tygodnia",
        help_text="Wybierz dni tygodnia, w których odbywa się wydarzenie"
    )
    # Dane kontaktowe
    website = models.URLField(
        blank=True, 
        null=True, 
        verbose_name="Strona www"
    )
    contact_email = models.EmailField(
        verbose_name="Adres e-mail"
    )

    # Kategoria i lokalizacja
    categories = models.ManyToManyField(
        "web.Category", 
        verbose_name="Rodzaj",
        related_name="events"
    )
    location_type = models.CharField(
        max_length=20,
        choices=LOCATION_CHOICES,
        default="inside",
        verbose_name="Gdzie"
    )
    entry_type = models.CharField(
        max_length=20,
        choices=ENTRY_CHOICES,
        verbose_name="Wstęp",
        default="free"
    )
    added_by = models.CharField(
        max_length=20,
        choices=ADDED_BY_CHOICES,
        verbose_name="Dodane przez",
        default="organizer"
    )

    # Lokalizacja geograficzna
    location = PointField(
        blank=True, 
        null=True, 
        verbose_name="Lokalizacja (szerokość i długość geograficzna)"
    )

    # Metadane
    created_by = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        verbose_name="Utworzone przez"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, 
        verbose_name="Data utworzenia",
        db_index=True
    )
    updated_at = models.DateTimeField(
        auto_now=True, 
        verbose_name="Data ostatniej aktualizacji"
    )
    thumbnails_cache = models.JSONField(default=dict, null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name="Aktywne")
    
    class Meta:
        verbose_name = "Wydarzenie"
        verbose_name_plural = "Wydarzenia"
        ordering = ["-created_at"]  
        indexes = [
            models.Index(fields=["name"], name="idx_event_name"),
            models.Index(fields=["created_at"], name="idx_event_created_at")
        ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name.replace("ł", "l"))
        
        old_main_image = self.__get_main_image()
        old_gallery_image_1 = self.__get_gallery_image_1()
        old_gallery_image_2 = self.__get_gallery_image_2()
        old_gallery_image_3 = self.__get_gallery_image_3()
        
        super(Event, self).save()
        
        if self.main_image != old_main_image:
            delete_thumbnails(self, self, 1, "event_id", "main_image")
            
            if self.main_image:
                self.thumbnails_cache["main_image"] = make_thumbnail(
                    self.main_image,
                    [(350, 260), (700, 520)],
                    1,
                    self,
                    "Event",
                )
            else:
                self.thumbnails_cache["main_image"] = {}
        
        if self.gallery_image_1 != old_gallery_image_1:
            delete_thumbnails(self, self, 2, "event_id", "gallery_image_1")
            
            if self.gallery_image_1:
                self.thumbnails_cache["gallery_image_1"] = make_thumbnail(
                    self.gallery_image_1,
                    [(350, 260), (700, 520)],
                    2,
                    self,
                    "Event",
                )
            else:
                self.thumbnails_cache["gallery_image_1"] = {}
        
        if self.gallery_image_2 != old_gallery_image_2:
            delete_thumbnails(self, self, 2, "event_id", "gallery_image_2")
            
            if self.gallery_image_2:
                self.thumbnails_cache["gallery_image_2"] = make_thumbnail(
                    self.gallery_image_1,
                    [(350, 260), (700, 520)],
                    2,
                    self,
                    "Event",
                )
            else:
                self.thumbnails_cache["gallery_image_2"] = {}
        
        if self.gallery_image_3 != old_gallery_image_3:
            delete_thumbnails(self, self, 3, "event_id", "gallery_image_3")
            
            if self.gallery_image_3:
                self.thumbnails_cache["gallery_image_3"] = make_thumbnail(
                    self.gallery_image_3,
                    [(350, 260), (700, 520)],
                    3,
                    self,
                    "Event",
                )
            else:
                self.thumbnails_cache["gallery_image_3"] = {}
        
        old_gallery_image_4 = self.__get_gallery_image_4()
        if self.gallery_image_4 != old_gallery_image_4:
            delete_thumbnails(self, self, 4, "event_id", "gallery_image_4")
            
            if self.gallery_image_4:
                self.thumbnails_cache["gallery_image_4"] = make_thumbnail(
                    self.gallery_image_4,
                    [(350, 260), (700, 520)],
                    4,
                    self,
                    "Event",
                )
            else:
                self.thumbnails_cache["gallery_image_4"] = {}
                
        super(Event, self).save()
        
    
    def __get_main_image(self):
        try:
            event = Event.objects.get(pk=self.pk)
            return event.main_image
        except Event.DoesNotExist:
            return None
    
    def __get_gallery_image_1(self):
        try:
            event = Event.objects.get(pk=self.pk)
            return event.gallery_image_1
        except Event.DoesNotExist:
            return None
    
    def __get_gallery_image_2(self):
        try:
            event = Event.objects.get(pk=self.pk)
            return event.gallery_image_2
        except Event.DoesNotExist:
            return None
    
    def __get_gallery_image_3(self):
        try:
            event = Event.objects.get(pk=self.pk)
            return event.gallery_image_3
        except Event.DoesNotExist:
            return None
    
    def __get_gallery_image_4(self):
        try:
            event = Event.objects.get(pk=self.pk)
            return event.gallery_image_4
        except Event.DoesNotExist:
            return None
    
    def __str__(self):
        return self.name

    def get_day_of_week_display(self):
        day_dict = dict(DAYS_OF_WEEK)
        return [day_dict.get(day, day) for day in self.day_of_week]

    
    @property
    def users_count(self):
        return self.participants.count()
    
    
    @property
    def address(self):

web/events/forms.py
from django import forms

from web.constans import ADDED_BY_CHOICES, ENTRY_CHOICES, LOCATION_CHOICES, DATE_CHOICES
from web.models.categories import Category


class EventFilterForm(forms.Form):
    date_filter = forms.ChoiceField(
        choices=DATE_CHOICES,
        widget=forms.Select(attrs={'id': 'date-filter'}),
        label="Kiedy"
    )
    selected_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date', 'id': 'selected-date'}),
        label="Wybierz datę"
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.filter(is_active=True),
        widget=forms.CheckboxSelectMultiple,
        label="Rodzaj",
        required=False
    )
    location_type = forms.ChoiceField(
        choices=LOCATION_CHOICES,
        widget=forms.RadioSelect,
        label="Gdzie",
        required=False
    )
    entry_type = forms.ChoiceField(
        choices=ENTRY_CHOICES,
        widget=forms.RadioSelect,
        label="Wstęp",
        required=False
    )
    added_by = forms.ChoiceField(
        choices=ADDED_BY_CHOICES,
        widget=forms.RadioSelect,
        label="Dodane przez",
        required=False
    )
    
    def __init__(self, *args, **kwargs):
        session_data = kwargs.pop('session_data', {})
        super().__init__(*args, **kwargs)

        for field_name, value in session_data.items():
            if field_name in self.fields:
                self.fields[field_name].initial = value
    

class AbuseReportForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Temat zgłoszenia',
        }),
        label="Temat zgłoszenia", 
    )
    description = forms.CharField(
        max_length=500,
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Podaj treść zgłoszenia',
            'rows': 3,
        }),
        label="Treść zgłoszenia",
    )


class MessageForm(forms.Form):
    event = forms.IntegerField(
        required=True,
        widget=forms.HiddenInput(),
    )
    user = forms.IntegerField(
        required=True,
        widget=forms.HiddenInput(),
    )
    message = forms.CharField(
        max_length=300,
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Wpisz maksymalnie 300 znaków',
            'rows': 3,
        }),
        label="Wiadomość",
    )

web/templates/events/event_details.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ event.name }}{% endblock %}
{% block description %}Outtur.com wydarzenie {{ event.name }}. {{ event.short_description|truncatechars:160 }}{% endblock %}

{% block content %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v21.0&appId=1766955874049180"></script>

<div class="container my-5 bg-white shadow-sm p-4 rounded">
    <!-- Nagłówek z nazwą wydarzenia -->
    <div class="row align-items-center mb-4">
        <div class="col-xl-10">
            <h1 class="text-dark fw-bold fs-3">{{ event.name }}</h1>
        </div>
        <div class="col-xl-2 text-end">
            <div class="d-flex justify-content-end align-items-center">
                <span id="likes-count-{{ event.id }}" class="me-2">{{ event.likes_count }}</span>
                {% if user.is_authenticated %}
                    <!-- Ikona do polubienia wydarzenia -->
                    <i class="fa fa-heart{% if event.is_liked %} text-danger{% else %} text-dark{% endif %}" 
                    data-event-id="{{ event.id }}" 
                    data-add-like-url="{% url 'events:add_like_event' event_id=event.id %}"
                    style="cursor: pointer;"
                    data-bs-toggle="tooltip" 
                    data-bs-placement="top" 
                    title="{% if event.is_liked %}Kliknij, aby usunąć polubienie{% else %}Kliknij, aby polubić{% endif %}"
                    onclick="toggleLike(this)"></i>
                {% else %}
                    <!-- Ikona z chmurką informującą o konieczności zalogowania -->
                    <i class="fa fa-heart text-dark" 
                    data-bs-toggle="tooltip" 
                    data-bs-placement="top" 
                    title="Zaloguj się, aby polubić wydarzenie" 
                    style="cursor: not-allowed;"></i>
                {% endif %}

                <span id="users-count-{{ event.id }}" class="ms-4">{{ event.users_count }}</span>
                {% if user.is_authenticated %}
                    <!-- Ikona do dodania użytkownika do wydarzenia -->
                    <i class="fa-solid add-user-to-event fa-users text-dark fs-5" 
                        data-event-id="{{ event.id }}" 
                        data-add-user-url="{% url 'events:add_user_to_event' event_id=event.id %}"
                        style="cursor: pointer;"
                        data-bs-toggle="tooltip" 
                        data-bs-placement="top" 
                        title="Kliknij, aby dołączyć do wydarzenia"
                        onclick="addUserToEvent(this)"
                        ></i>
                {% else %}
                    <!-- Ikona z chmurką informującą o konieczności zalogowania -->
                    <i class="fa-solid fa-users text-dark fs-5" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="top" 
                        title="Zaloguj się, aby dołączyć do wydarzenia" 
                        style="cursor: not-allowed;"></i>
                {% endif %}

                <div class="ms-3">
                    <div class="fb-share-button" 
                        data-href="{{ request.build_absolute_uri }}" 
                        data-layout="button" 
                        data-size="small">
                        <a target="_blank" 
                            href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" 
                            class="fb-xfbml-parse-ignore">
                            Udostępnij
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Główna sekcja wydarzenia -->
    <div class="row">
        <!-- Zdjęcie główne -->
        <div class="col-12 mb-4">
            {% if event.main_image %}
                <img src="{{ event.main_image.url }}" class="img-fluid rounded shadow" alt="{{ event.name }}">
            {% else %}
                <img src="{% static 'images/placeholder.jpg' %}" class="img-fluid rounded shadow" alt="Placeholder">
            {% endif %}
        </div>

        <!-- Szczegóły wydarzenia -->
        <div class="col-lg-12 d-flex flex-wrap justify-content-between align-items-center">
            <div class="col-12 p-0 m-0 d-flex">
                <p class="">{{ event.address }}</p>
                {% if event.location %}
                    <a href="{% url 'events:event_map' slug=event.slug pk=event.id %}" class="ms-2 card-text map-link text-dark text-decoration-underline">mapa</a>
                {% endif %}
            </div>
            <div class="col-xl-5 p-0 m-0 d-flex">
                <strong>Dodane przez:&nbsp;{{ event.get_added_by_display }}:&nbsp;</strong> 
                <a href="#" class="text-dark text-decoration-underline">
                    {% if event.created_by.first_name %}
                        {{ event.created_by.first_name }}{% else %}anominowy
                    {% endif %}
                </a>
            </div>
            <p class="col-xl-5 p-0 m-0 text-end">Data wydarzenia:&nbsp;{{ event.date_info }}</p>

            <!-- Opis wydarzenia -->
            <div class="row mt-4 col-12">
                <div class="col-12">
                    <h3 class="fw-bold mb-3">W skrócie</h3>
                    <p>{{ event.short_description|linebreaks }}</p>
                </div>
            </div>

            <!-- Opis wydarzenia -->
            <div class="row mt-4">
                <div class="col-12">
                    <h3 class="fw-bold mb-3">Opis wydarzenia</h3>
                    <p>{{ event.description|linebreaks }}</p>
                </div>
            </div>

            <p class="col-12 mt-4">
                <strong>Szczegóły:</strong>
            </p>
            <p class="col-12 p-0 m-0">Kontakt:&nbsp;<a href="mailto:{{ event.contact_email }}" class="text-dark">{{ event.contact_email }}</a></p>
            {% if event.website %}
                <p class="col-12 p-0 m-0">Strona:&nbsp;<a href="{{ event.website }}" target="_blank" class="text-dark">{{ event.website }}</a></p>
            {% endif %}
            <p class="col-12 p-0 m-0">Wstęp:&nbsp;{{ event.get_entry_type_display }}</p>
            <p class="col-12 p-0 m-0">Rodzaj:&nbsp;{% for category in event.categories.all %}<span>{{ category.name }}{% if not forloop.last %},&nbsp;{% endif %}{% endfor %}</p>
            <p class="col-12 p-0 m-0">Cykl imprezy:&nbsp;{{ event.get_event_type_display }}</p>
        </div>
    </div>

    {% if event.gallery_images %}
    <!-- Galeria zdjęć -->
    <div class="row my-5">
        <div class="col-12">
            <h3 class="fw-bold mb-3">Galeria</h3>
        </div>
        {% for image in event.gallery_images %}
            {% if image %}
                <div class="col-md-3 mb-3">
                    <img src="{{ image.url }}" class="img-fluid rounded shadow" alt="Zdjęcie galerii">
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    <!-- Przycisk zgłaszania nadużycia -->
<div class="row my-5">
    <div class="col-12 text-start">
        {% if user.is_authenticated %}
            <!-- Pokazuje formularz tylko jeśli użytkownik jest zalogowany -->
            <button type="button" class="btn btn-primary btn-lg rounded-pill" id="toggle-form">
                Zgłoś nadużycie
            </button>
        {% else %}
            <!-- Przycisk z tooltipem dla niezalogowanego użytkownika -->
            <a href="#" 
               class="btn btn-primary btn-lg rounded-pill" 
               data-bs-toggle="tooltip" 
               data-bs-placement="top" 
               title="Aby zgłosić nadużycie, musisz być zalogowany">
                Zgłoś nadużycie
            </a>
        {% endif %}
    </div>
</div>

<!-- Formularz zgłaszania nadużycia -->
{% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data" id="event-form" style="display: none;">
        {% csrf_token %}
        <!-- Nazwa i krótki opis -->
        <div class="row g-3 mb-3">
            <div class="col-xl-6 col-12">
                <label for="{{ form.title.id_for_label }}" class="form-label col-12">
                    {{ form.title.label }}
                </label>
                <input type="text" 
                       id="{{ form.title.id_for_label }}" 
                       name="{{ form.title.html_name }}" 
                       class="form-control" 
                       value="{{ form.title.value|default_if_none:'' }}" 
                       placeholder="{{ form.title.field.widget.attrs.placeholder|default:'Podaj nazwę wydarzenia' }}" 
                       maxlength="{{ form.title.field.max_length }}" 
                       {% if form.title.field.required %}required{% endif %}>
                {% if form.title.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.title.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <!-- Pole: Krótki opis wydarzenia -->
            <div class="col-12">
                <label for="{{ form.description.id_for_label }}" class="form-label col-12">
                    {{ form.description.label }}
                </label>
                <textarea id="{{ form.description.id_for_label }}" 
                        name="{{ form.description.html_name }}" 
                        class="form-control" 
                        placeholder="{{ form.description.field.widget.attrs.placeholder|default:'Podaj krótki opis wydarzenia' }}" 
                        maxlength="{{ form.description.field.max_length }}" 
                        rows="3" 
                        {% if form.description.field.required %}required{% endif %}>{{ form.description.value|default_if_none:'' }}</textarea>
            </div>
        </div>
        <div class="col-12 d-flex justify-content-between align-items-middle">
            <button type="submit" class="btn rounded-20 btn-primary">Wyślij</button>
            <button type="button" class="btn rounded-20 bg-orange text-white">Anuluj</button>
        </div>
    </form>
{% endif %}
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/event_details.js' %}"></script>
    <script src="{% static 'js/user_actions.js' %}"></script>
{% endblock %}

web/templates/events/events_listing_list.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}Outtur.com Lista wydarzeń{% endblock %}
{% block description %}Outtur.com Lista wydarzeń{% endblock %}

{% block home_main %}
<!-- Lista wydarzeń -->
<div class="event_listing col-12 d-flex justify-content-start align-items-start flex-wrap">
    {% include "events/includes/event_listing.html" %}
    <div id="map" style="width: 100%;">
        {{ map_html|safe }}
    </div>
</div>
{% endblock %}

{% block pagination %}
<!-- Paginacja -->
<div class="pagination-container col-12 d-flex justify-content-center align-items-start">
    {% include "utils/pagination.html" %}
</div>
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/filters_events.js' %}"></script>
    <script src="{% static 'js/user_actions.js' %}"></script>
{% endblock %}

web/templates/events/events_listing_map.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}Outtur.com Mapa wydarzeń{% endblock %}
{% block description %}Outtur.com Mapa wydarzeń{% endblock %}

{% block home_main %}
<!--Mapa wydarzenia -->
<div class="event_listing col-12 d-flex justify-content-start align-items-start flex-wrap">
    <div id="events_map" style="width: 100%;">
        {{ map_html|safe }}
    </div>
</div>
{% endblock %}

{% block pagination %}
<!-- Paginacja -->
<div class="pagination-container col-12 d-flex justify-content-center align-items-start">
    {% include "utils/pagination.html" %}
</div>
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/filters_events.js' %}"></script>
{% endblock %}