outtur/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('web.cms.urls')),
    path('auth/', include('web.auth.urls')),
    path('profil/', include('web.profile.urls')),
    path('wydarzenia/', include('web.events.urls')),
    path('', include('web.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/auth/urls.py
from django.urls import path
from .views import UserLogout, UserRegistrationView, LoginView, ActivateUserAccountByTokenView


app_name = "auth"


urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('aktywacja-konta/<token>', ActivateUserAccountByTokenView.as_view(), name='activate_account'),
    path('login/', LoginView.as_view(), name='login'),
    path('wyloguj/', UserLogout.as_view(), name='logout'),
]

web/cms/urls.py
from django.urls import path
from .views import EventCreateView, EventUpdateView

app_name = "cms"


urlpatterns = [
    path('dodaj-wydarzenie/', EventCreateView.as_view(), name='create_event'),
    path('edytuj-wydarzenie/<int:pk>/', EventUpdateView.as_view(), name='update_event'),
]

web/events/urls.py
from django.urls import path

from web.events.views import EventDetails, EventMapView, EventsMapView, EventsView
from .views_ajax import add_user_to_event, ajax_filter_events, ajax_filter_events_map, add_like_event

app_name = "events"


urlpatterns = [
   path('add-user-to-event/<int:event_id>/', add_user_to_event, name='add_user_to_event'),
   path('add-like-event/<int:event_id>/', add_like_event, name='add_like_event'),
   path('ajax/filter-events/', ajax_filter_events, name='ajax_filter_events'),
   path('ajax/filter-events-map/', ajax_filter_events_map, name='ajax_filter_events_map'),
   
   path('<slug:slug>/<int:pk>/', EventDetails.as_view(), name='event_details'),
   path('<slug:slug>/mapa/<int:pk>/', EventMapView.as_view(), name='event_map'),
   path('mapa/', EventsMapView.as_view(), name='events_map'),
   path('lista/', EventsView.as_view(), name='events_list'),
]

web/home/urls.py
from django.urls import path

from web.home.views import HomeView


app_name = "home"


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

web/home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Strona główna'
        return context

web/templates/home/base.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% csrf_token %}
<div class="container mt-2 p-0 m-0">
    <div class="d-flex flex-wrap justify-content-start align-items-start">
        {% block side_bar %}
        <!-- Lewa kolumna - Menu kategorii -->
        <div class="d-none d-xl-flex col-xl-2">
            {% if filter_form %}
                {% include "events/includes/filters_event.html" %}
            {% endif %}
        </div>
        {% endblock %}

        <!-- Prawa kolumna - Lista wydarzeń i paginacja -->
        <div class="col-12 col-xl-10 d-flex justify-content-start align-items-start flex-wrap p-0 m-0 mx-auto ps-xl-2">
            {% block home_main %}
            {% endblock %}

            {% block pagination %}
            {% endblock %}
        </div>
    </div>
</div>

<div id="loading-spinner" class="text-center my-4" style="display: none;">
    <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Ładowanie...</span>
    </div>
</div>
    {% block home_js %}
    {% endblock %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

web/templates/home/home.html
{% extends "home/base.html" %}

{% load static %}

{% block title %}{% endblock %}
{% block description %}{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="container mt-2 p-0 m-0">
        <div class="hero-container col-12 bg-orange d-flex flex-wrap justify-content-center align-items-center">
            <div class="col-xl-6 d-flex justify-content-center align-items-center flex-wrap text-white">
                <p class="h4 text-center col-12 fw-bolder">Pamiętaj dodanie wydarzenia jest</p>
                <p class="h1 text-center col-12 fw-bolder">bezpłatne</p>
            </div>
            <div class="col-12 col-xl-6 d-flex justify-content-center align-items-center flex-wrap text-white">
                <a href="{% if request.user.is_authenticated %}{% url 'cms:create_event' %}{% else %}{% url 'auth:login' %}{% endif %}" class="col-10 col-xl-6 text-center btn btn-primary rounded-20 fw-bolder p-2">Dodaj wydarzenie</a>
            </div>
        </div>
        <div class="mt-5 d-flex flex-wrap justify-content-between align-items-start">
            
            <a href="{% url 'events:events_list' %}" class="hero-container position-relative col-12 col-xl-6 bg-danger text-white d-flex justify-content-center align-items-start flex-wrap">
                <p class="h4 text-center col-12 fw-bolder mt-2">wszystko co w Twojej okolicy</p>
                <span class="position-absolute custom-position" style="top: 25%; left: 15%;">turystyka</span>
                <span class="position-absolute custom-position" style="top: 35%; left: 70%;">dla dzieci</span>
                <span class="position-absolute custom-position" style="top: 40%; left: 30%;">sportowe</span>
                <span class="position-absolute custom-position" style="top: 50%; left: 50%;">gminne</span>
                <span class="position-absolute custom-position" style="top: 65%; left: 10%;">zgromadzenia</span>
                <span class="position-absolute custom-position" style="top: 25%; left: 80%;">zabawa</span>
                <span class="position-absolute custom-position" style="top: 50%; left: 20%;">sąsiedzki</span>
                <span class="position-absolute custom-position" style="top: 68%; left: 40%;">wyprzedaże garażowe</span>
                <span class="position-absolute custom-position" style="top: 85%; left: 60%;">gastronomiczne</span>
                <span class="position-absolute custom-position" style="top: 88%; left: 30%;">kulturalne</span>
            </a>
            <a href="{% url 'events:events_map' %}" class="col-12 col-xl-5 d-flex justify-content-center mt-5 mt-xl-0">
                <img src="{% static 'images/wydarzenia-mapa.webp' %}" alt="hero1" class="img-fluid mx-auto" width="475px" height="350px">
            </a>  
        </div>
    </div>
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/filters_events.js' %}"></script>
    <script src="{% static 'js/events.js' %}"></script>
{% endblock %}