outtur/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('web.cms.urls')),
    path('auth/', include('web.auth.urls')),
    path('profil/', include('web.profile.urls')),
    path('wydarzenia/', include('web.events.urls')),
    path('', include('web.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/cms/urls.py
from django.urls import path
from .views import EventCreateView, EventUpdateView

app_name = "cms"


urlpatterns = [
    path('dodaj-wydarzenie/', EventCreateView.as_view(), name='create_event'),
    path('edytuj-wydarzenie/<int:pk>/', EventUpdateView.as_view(), name='update_event'),
]

web/profile/urls.py
from django.urls import path
from .views import MessageFormView, UserEventMessagesView, UserEventsCreated, UserEventsJoined, ProfileUpdateView

app_name = "profile"


urlpatterns = [
    path('aktualizuj-profil/', ProfileUpdateView.as_view(), name='update_profile'),
    path('moje-wydarzenia/', UserEventsCreated.as_view(), name='user_events'),
    path('moje-wydarzenia-zapisane/', UserEventsJoined.as_view(), name='user_events_joined'),
    path('moje-wiadomosci/', UserEventMessagesView.as_view(), name='user_event_messages'),
    path('wyslij-wiadomosc/<int:event_id>/', MessageFormView.as_view(), name='send_message'),
]

web/profile/forms.py
from django import forms

from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):
    phone_number = forms.CharField(label="Numer telefonu" ,max_length=9, required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'phone_number']
        labels = {
            'first_name': 'Nazwa',
            'username': 'Login',
            'email': 'Adres e-mail',
            'phone_number': 'Numer telefonu',
        }

web/profile/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from web.events.forms import MessageForm
from web.models.events import Event, EventMessage, EventParticipant
from web.profile.forms import ProfileForm
from django.db.models import Count

from django.contrib.auth.models import User


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = "profile/forms/profile_update_form.html"
    success_url = reverse_lazy("profile:update_profile")

    def get_object(self, queryset=None):
        return self.request.user

    def get_initial(self):
        initial = super().get_initial()
        initial["phone_number"] = self.request.user.profile.phone_number
        return initial

    def form_valid(self, form):
        response = super().form_valid(form)

        phone_number = form.cleaned_data.get("phone_number")
        profile = self.request.user.profile
        profile.phone_number = phone_number
        profile.save()

        messages.success(self.request, "Profil został zaktualizowany.")
        return response

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))
    
    
@method_decorator(login_required, name='dispatch')
class UserEventsCreated(ListView):
    model = Event
    template_name = 'profile/user_events.html'
    context_object_name = 'events'
    paginate_by = 20
    

    def get_queryset(self):
        return Event.objects.filter(created_by=self.request.user.id).annotate(
            participants_count=Count('participants'),
            likes_count=Count('likes')
        ).order_by('-created_at')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Moje wydarzenia'
        context['form'] = MessageForm()
        return context


@method_decorator(login_required, name='dispatch')
class UserEventsJoined(ListView):
    model = Event
    template_name = 'profile/user_events_joined.html'
    context_object_name = 'events'
    paginate_by = 20

    def get_queryset(self):
        return Event.objects.filter(
            participants__user=self.request.user
        ).annotate(
            participants_count=Count('participants'),
            likes_count=Count('likes')
        ).order_by('-created_at').distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Wydarzenia, na które się zapisałem'
        return context


@method_decorator(login_required, name='dispatch')
class UserEventMessagesView(ListView):
    model = EventMessage
    template_name = 'profile/user_event_messages.html'
    context_object_name = 'events_messages'
    paginate_by = 20

    def get_queryset(self):
        user_events = EventParticipant.objects.filter(user=self.request.user).values_list('event', flat=True)

        return EventMessage.objects.filter(event__in=user_events).select_related('event', 'user').order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Wiadomości z moich wydarzeń'
        return context
    
    
class MessageFormView(LoginRequiredMixin, FormView):
    form_class = MessageForm
    success_url = reverse_lazy("profile:user_events") 

    def form_valid(self, form):
        event_id = form.cleaned_data['event']
        message_content = form.cleaned_data['message']

        event = get_object_or_404(Event, id=event_id)

        EventMessage.objects.create(
            event=event,
            user=self.request.user, 
            message=message_content
        )

        messages.success(self.request, "Wiadomość została wysłana!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Wysłanie wiadomości nie powiodło się. Popraw błędy.")
        return super().form_invalid(form)
    

web/templates/profile/base.html
{% extends "home/base.html" %}

{% load static %}

{% block side_bar %}
<!-- Lewa kolumna - Menu kategorii -->
<div class="d-none d-xl-flex col-xl-2">
    <div class="d-xl-flex col-12 justify-content-start align-items-start flex-column border-end p-0 m-0 bg-white">
        <a href="{% url 'cms:create_event' %}" class="col-12 p-2">
            <span class="text-dark {% if request.resolver_match.url_name == 'create_event' %}fw-bolder{% endif %}">Dodaj Wydarzenie</span>
        </a>
        <a href="{% url 'profile:update_profile' %}" class="col-12 p-2">
            <span class="text-dark {% if request.resolver_match.url_name == 'update_profile' %}fw-bolder{% endif %}">Moje konto</span>
        </a>
        <a href="{% url 'profile:user_event_messages' %}" class="col-12 p-2">
            <span class="text-dark {% if request.resolver_match.url_name == 'user_event_messages' %}fw-bolder{% endif %}">Wiadomości</span>
        </a>
        <a href="{% url 'profile:user_events_joined' %}" class="col-12 p-2">
            <span class="text-dark {% if request.resolver_match.url_name == 'user_events_joined' %}fw-bolder{% endif %}">Wydarzenia w których uczestniczę</span>
        </a>
        <a href="{% url 'profile:user_events' %}" class="col-12 p-2">
            <span class="text-dark {% if request.resolver_match.url_name == 'user_events' %}fw-bolder{% endif %}">Wydarzenia dodane</span>
        </a>
    </div>
</div>
{% endblock %}

{% block home_main %}
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/user_actions.js' %}"></script>
{% endblock %}

web/templates/profile/user_event_messages.html
{% extends "profile/base.html" %}


{% block home_main %}
    <!-- Lista wydarzeń -->
    <div class="event_listing col-12 d-flex justify-content-start align-items-start flex-wrap">
        {% include 'events/includes/event_messages.html' %}
    </div>
{% endblock %}

web/templates/profile/user_events.html
{% extends "profile/base.html" %}

{% block home_main %}
    <!-- Lista wydarzeń -->
    <div class="event_listing col-12 d-flex justify-content-start align-items-start flex-wrap">
        {% include "events/includes/event_listing.html" %}
    </div>
{% endblock %}

web/templates/profile/user_events_joined.html
{% extends "profile/base.html" %}


{% block home_main %}
    <!-- Lista wydarzeń -->
    <div class="event_listing col-12 d-flex justify-content-start align-items-start flex-wrap">
        {% include "events/includes/event_listing.html" %}
    </div>
{% endblock %}