outtur/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('web.cms.urls')),
    path('auth/', include('web.auth.urls')),
    path('profil/', include('web.profile.urls')),
    path('wydarzenia/', include('web.events.urls')),
    path('', include('web.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/cms/urls.py
from django.urls import path
from .views import EventCreateView, EventUpdateView

app_name = "cms"


urlpatterns = [
    path('dodaj-wydarzenie/', EventCreateView.as_view(), name='create_event'),
    path('edytuj-wydarzenie/<int:pk>/', EventUpdateView.as_view(), name='update_event'),
]

web/events/urls.py
from django.urls import path

from web.events.views import EventDetails, EventMapView, EventsMapView, EventsView
from .views_ajax import add_user_to_event, ajax_filter_events, ajax_filter_events_map, add_like_event

app_name = "events"


urlpatterns = [
   path('add-user-to-event/<int:event_id>/', add_user_to_event, name='add_user_to_event'),
   path('add-like-event/<int:event_id>/', add_like_event, name='add_like_event'),
   path('ajax/filter-events/', ajax_filter_events, name='ajax_filter_events'),
   path('ajax/filter-events-map/', ajax_filter_events_map, name='ajax_filter_events_map'),
   
   path('<slug:slug>/<int:pk>/', EventDetails.as_view(), name='event_details'),
   path('<slug:slug>/mapa/<int:pk>/', EventMapView.as_view(), name='event_map'),
   path('mapa/', EventsMapView.as_view(), name='events_map'),
   path('lista/', EventsView.as_view(), name='events_list'),
]

web/profile/urls.py
from django.urls import path
from .views import MessageFormView, UserEventMessagesView, UserEventsCreated, UserEventsJoined, ProfileUpdateView

app_name = "profile"


urlpatterns = [
    path('aktualizuj-profil/', ProfileUpdateView.as_view(), name='update_profile'),
    path('moje-wydarzenia/', UserEventsCreated.as_view(), name='user_events'),
    path('moje-wydarzenia-zapisane/', UserEventsJoined.as_view(), name='user_events_joined'),
    path('moje-wiadomosci/', UserEventMessagesView.as_view(), name='user_event_messages'),
    path('wyslij-wiadomosc/<int:event_id>/', MessageFormView.as_view(), name='send_message'),
]

web/events/forms.py
from django import forms

from web.constans import ADDED_BY_CHOICES, ENTRY_CHOICES, LOCATION_CHOICES, DATE_CHOICES
from web.models.categories import Category


class EventFilterForm(forms.Form):
    date_filter = forms.ChoiceField(
        choices=DATE_CHOICES,
        widget=forms.Select(attrs={'id': 'date-filter'}),
        label="Kiedy"
    )
    selected_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date', 'id': 'selected-date'}),
        label="Wybierz datę"
    )
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.filter(is_active=True),
        widget=forms.CheckboxSelectMultiple,
        label="Rodzaj",
        required=False
    )
    location_type = forms.ChoiceField(
        choices=LOCATION_CHOICES,
        widget=forms.RadioSelect,
        label="Gdzie",
        required=False
    )
    entry_type = forms.ChoiceField(
        choices=ENTRY_CHOICES,
        widget=forms.RadioSelect,
        label="Wstęp",
        required=False
    )
    added_by = forms.ChoiceField(
        choices=ADDED_BY_CHOICES,
        widget=forms.RadioSelect,
        label="Dodane przez",
        required=False
    )
    
    def __init__(self, *args, **kwargs):
        session_data = kwargs.pop('session_data', {})
        super().__init__(*args, **kwargs)

        for field_name, value in session_data.items():
            if field_name in self.fields:
                self.fields[field_name].initial = value
    

class AbuseReportForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Temat zgłoszenia',
        }),
        label="Temat zgłoszenia", 
    )
    description = forms.CharField(
        max_length=500,
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Podaj treść zgłoszenia',
            'rows': 3,
        }),
        label="Treść zgłoszenia",
    )


class MessageForm(forms.Form):
    event = forms.IntegerField(
        required=True,
        widget=forms.HiddenInput(),
    )
    user = forms.IntegerField(
        required=True,
        widget=forms.HiddenInput(),
    )
    message = forms.CharField(
        max_length=300,
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Wpisz maksymalnie 300 znaków',
            'rows': 3,
        }),
        label="Wiadomość",
    )

web/events/views.py
import folium

from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.template.loader import render_to_string
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.urls import reverse

from bs4 import BeautifulSoup

from web.events.filters import get_filtered_queryset
from web.events.forms import AbuseReportForm, EventFilterForm
from web.events.serializers import EventSerializer
from web.models.events import Event


class EventsView(ListView):
    template_name = 'events/events_listing_list.html'
    paginate_by = 20

    def get_queryset(self):
        return get_filtered_queryset(self.request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session_filters = self.request.session.get("event_filters", {})
        context['filter_form'] = EventFilterForm(initial=session_filters)
        context['form_action'] = reverse('events:events_list')
        context['search_form_on'] = True
        context['events'] = self.get_paginated_events().object_list
        context['page_obj'] = self.get_paginated_events()
        context['paginator'] = context['page_obj'].paginator
        return context

    def get_paginated_events(self):
        page = self.request.GET.get('page', 1)
        paginator = Paginator(self.get_queryset(), self.paginate_by)

        try:
            return paginator.page(page)
        except PageNotAnInteger:
            return paginator.page(1)
        except EmptyPage:
            return paginator.page(paginator.num_pages)

    
class EventDetails(DetailView):
    model = Event
    template_name = 'events/event_details.html'
    context_object_name = 'event'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Szczegóły wydarzenia'
        context['form'] = AbuseReportForm()
        
        event = self.object
        
        event.participants_count = event.participants.count()
        event.likes_count = event.likes.count()
        user = self.request.user
        if user.is_authenticated:
            event.is_liked = event.likes.filter(user=user).exists()
        else:
            event.is_liked = False
        context['event'] = event
        return context
    
    
class EventMapView(TemplateView):
    template_name = "events/includes/event_map.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event_id = self.kwargs.get('pk')
        event = get_object_or_404(Event, id=event_id)

        if not event.location:
            raise Http404("Lokalizacja wydarzenia nie jest dostępna.")

        latitude = event.location.y
        longitude = event.location.x

        folium_map = folium.Map(location=[latitude, longitude], zoom_start=15)
        folium.Marker(
            [latitude, longitude],
            popup=event.name,
            tooltip="Kliknij, aby zobaczyć szczegóły"
        ).add_to(folium_map)
        
        user_location = self.request.session.get('user_location') 
        if user_location:
            latitude, longitude = map(float, user_location.split(','))

            if latitude and longitude:
                folium.Marker(
                    location=[latitude, longitude],
                    popup="Twoja lokalizacja",
                    tooltip="Jesteś tutaj",
                    icon=folium.Icon(color="red", icon="user")
                ).add_to(folium_map)

        context['event'] = event
        
        map_html = folium_map._repr_html_()
        context['map_html'] = map_html.replace(
        'style="position:relative;width:100%;height:0;padding-bottom:60%;"',
        'style="position:relative;" id="map-container"'
        )
        
        return context


class EventsMapView(TemplateView):
    template_name = "events/events_listing_map.html"
    paginate_by = 20
    
    def get_queryset(self):
        return get_filtered_queryset(self.request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events = self.get_queryset()
        
        page = self.request.GET.get('page', 1) 
        paginator = Paginator(events, self.paginate_by)
        
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
            
        session_data = self.request.session.get("event_filters", {})
        
        context['filter_form'] = EventFilterForm(self.request.GET or None, session_data=session_data)
        context['search_form_on'] = True
        context['events'] = page_obj.object_list  
        context['page_obj'] = page_obj  
        context['paginator'] = paginator  


        map_center = [52.0, 19.0] 
        folium_map = folium.Map(location=map_center, zoom_start=6)

        for event in page_obj.object_list:
            if event.location:
                latitude = event.location.y
                longitude = event.location.x

                popup_content = render_to_string("events/includes/popup_content.html", {"event": event})

                folium.Marker(
                    location=[latitude, longitude],
                    popup=folium.Popup(popup_content, max_width=600),
                    tooltip=event.name,
                    icon=folium.Icon(color="blue", icon="info-sign")
                ).add_to(folium_map)

        user_location = self.request.session.get('user_location') 
        if user_location:
            latitude, longitude = map(float, user_location.split(','))

            if latitude and longitude:
                folium.Marker(
                    location=[latitude, longitude],
                    popup="Twoja lokalizacja",
                    tooltip="Jesteś tutaj",
                    icon=folium.Icon(color="red", icon="user")
                ).add_to(folium_map)
                
        map_html = folium_map._repr_html_()
        

        soup = BeautifulSoup(map_html, 'html.parser')
        for span in soup.find_all("span", string=lambda text: "Make this Notebook Trusted" in text if text else False):
            span.decompose()  

        map_html_cleaned = str(soup)
        context['map_html'] = map_html_cleaned.replace(
        'style="position:relative;width:100%;height:0;padding-bottom:60%;"',
        'style="position:relative;" id="map-container"'
        )
        return context

web/templates/events/includes/event_listing.html
{% load query_transform %}

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v21.0&appId=1766955874049180"></script>

{% for event in events %}
    <div class="card event-item w-100 d-flex flex-row bg-white shadow-sm border-0 mb-3">
        <!-- Tekst -->
        <div class="card-body {% if event.main_image %}col-xl-8{% else %}col-xl-12{% endif %} d-flex flex-column">
            <div class="col-12 d-flex flex-wrap justify-content-between align-items-center">
                <a href="{% url 'events:event_details' slug=event.slug pk=event.id %}" class="card-title event-title col-xl-9 text-dark fw-bold m-0 p-0">
                    <h5 class="col-12 m-0 p-0">{{ event.name }}</h5>
                </a>
                <div class="fb-share-button col-3" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="">
                    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Udostępnij</a>
                </div>
                {% comment %} <small class="mb-2 col-12 text-dark text-muted">Dodano:&nbsp;{{ event.created_at }}</small> {% endcomment %}
                <div class="col-12 d-flex justify-content-end align-items-center text-end">
                    {% comment %} <span id="likes-count-{{ event.id }}" class="me-2">{{ event.likes_count }}</span>
                    {% if user.is_authenticated %}
                        <i class="fa fa-heart{% if event.is_liked %} text-danger{% else %} text-dark{% endif %} me-2" 
                        data-event-id="{{ event.id }}" 
                        data-add-like-url="{% url 'events:add_like_event' event_id=event.id %}"
                        style="cursor: pointer;"
                        data-bs-toggle="tooltip" 
                        data-bs-placement="top" 
                        title="{% if event.is_liked %}Kliknij, aby usunąć polubienie{% else %}Kliknij, aby polubić{% endif %}"
                        onclick="toggleLike(this)"></i>
                    {% else %}
                        <i class="fa fa-heart text-dark me-2" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="top" 
                        title="Zaloguj się, aby polubić wydarzenie" 
                        style="cursor: not-allowed;"></i>
                    {% endif %} {% endcomment %}
                    
                </div>
            </div>
            <div class="col-12 d-flex flex-wrap justify-content-between align-items-center mt-2">
                <p class="col-12 col-xl-8 text-dark mb-2">{{ event.address }}{% if event.distance %}&nbsp;{{ event.distance|floatformat:2 }}km{% endif %}</p>
                <div class="col-12 col-xl-3 d-flex justify-content-end align-items-center">
                    {% if event.event_type == 'one_day' %}
                    <span>{{ event.one_day_date }}</span>
                    {% elif event.event_type == 'is_multi_day' %}
                        <span>{{ event.start_date }}&nbsp;-&nbsp;{{ event.end_date  }}</span>
                    {% else %}
                        <div class="event-days col-12 text-end">
                            {{ event.get_day_of_week_display }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="d-flex flex-wrap justify-content-between align-items-start mt-2">
                <p class="col-12 mt-2 mb-1">Rodzaj:&nbsp;{% for category in event.categories.all %}<span>{{ category.name }}{% if not forloop.last %},&nbsp;{% endif %}{% endfor %}</p>
                <p class="col-12 mt-2 mb-1 fw-bold">Opis</p>
                <p class="col-card-text text-dark {% if event.main_image %}col-8 col-xl-12{% endif %} pe-2">{{ event.short_description|truncatechars:120 }}</p>
                {% if event.main_image %}
                    <!-- Zdjęcie -->
                    <div class="col-4 d-xl-none p-0">
                            <img src="{{ event.main_image.url }}" alt="{{ event.name }}" class="w-100 h-100 object-fit-cover" style="aspect-ratio: 4/3; object-fit: cover;">
                    </div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-between align-items-middle mt-auto">
                <div class="col-6 text-left">
                    {% if event.location %}
                        <a href="{% url 'events:event_map' slug=event.slug pk=event.id %}" class="card-text map-link text-dark text-decoration-underline">mapa</a>
                    {% else %}
                        <span class="card-text text-dark">brak lokalizacji</span>
                    {% endif %}
                </div>
                <div class="col-6 text-end">
                    <span id="users-count-{{ event.id }}">{{ event.users_count }}</span>
                    {% if user.is_authenticated %}
                        <!-- Ikona do dodania użytkownika do wydarzenia -->
                        <i class="fa-solid add-user-to-event fa-users text-dark fs-5" 
                            data-event-id="{{ event.id }}" 
                            data-add-user-url="{% url 'events:add_user_to_event' event_id=event.id %}"
                            style="cursor: pointer;"
                            data-bs-toggle="tooltip" 
                            data-bs-placement="top" 
                            title="Kliknij, aby dołączyć do wydarzenia"
                            onclick="addUserToEvent(this)"
                            ></i>
                    {% else %}
                        <!-- Ikona z chmurką informującą o konieczności zalogowania -->
                        <i class="fa-solid fa-users text-dark fs-5" 
                            data-bs-toggle="tooltip" 
                            data-bs-placement="top" 
                            title="Zaloguj się, aby dołączyć do wydarzenia" 
                            style="cursor: not-allowed;"></i>
                    {% endif %}
                </div>
            </div>
            
        </div>
        {% if event.main_image %}
            <div class="d-none d-xl-flex col-xl-4">
                <!-- Zdjęcie -->
                <div class="col-12 p-0">
                    <img src="{{ event.main_image.url }}" alt="{{ event.name }}" class="w-100 h-100 object-fit-cover" style="aspect-ratio: 4/3; object-fit: cover;">
                </div>
            </div>
        {% endif %}
    </div>

    {% if request.resolver_match.url_name == 'user_events' %}
    <div class="col-12 d-flex align-items-middle justify-content-between mt-2 mb-5">
        <a href="{% url 'cms:update_event' pk=event.id %}" class="btn rounded-20 bg-orange text-white">Edytuj</a>
        <button type="button" class="btn rounded-20 bg-orange text-white" data-bs-toggle="modal" data-bs-target="#messageModal_{{ event.id }}">
            Wyślij wiadomość
        </button>
    </div>
    {% endif %}

    {% if form %}
        <!-- Modal -->
        <div class="modal fade" id="messageModal_{{ event.id }}" tabindex="-1" aria-labelledby="messageModalLabel_{{ event.id }}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="messageModalLabel_{{ event.id }}">{{ event.name }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'profile:send_message' event_id=event.id %}" method="post" class="col-12">
                            {% csrf_token %}
                            <input type="hidden" name="event" id="id_event" value="{{ event.id }}">
                            <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}">
                            <textarea id="{{ form.message.id_for_label }}" 
                                    name="{{ form.message.html_name }}" 
                                    class="form-control" 
                                    placeholder="{{ form.message.field.widget.attrs.placeholder|default:'Podaj wiadomość dla wydarzenia' }}" 
                                    maxlength="{{ form.message.field.max_length }}" 
                                    rows="3" 
                                    {% if form.message.field.required %}required{% endif %}>{{ form.description.value|default_if_none:'' }}</textarea>
                            <div class="d-flex justify-content-end mt-3">
                                <button type="submit" class="btn rounded-20 bg-orange text-white me-2">Wyślij</button>
                                <button type="button" class="btn btn-secondary rounded-20" data-bs-dismiss="modal">Anuluj</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if request.resolver_match.url_name == 'user_events' %}
        {% include 'events/includes/event_messages.html' with events_messages=event.messages.all %}
    {% endif %}
{% endfor %}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const showFormButton = document.getElementById("show-message-form");
        const hideFormButton = document.getElementById("hide-message-form");
        const messageFormContainer = document.getElementById("message-form-container");

        if (showFormButton && messageFormContainer) {
            showFormButton.addEventListener("click", () => {
                messageFormContainer.style.display = "block";
            });
        }

        if (hideFormButton && messageFormContainer) {
            hideFormButton.addEventListener("click", () => {
                messageFormContainer.style.display = "none";
            });
        }
    });
</script>

web/templates/events/includes/event_map.html
{% extends "home/base.html" %}

{% load static %}


{% block side_bar %}
    <!-- Lewa kolumna - Menu kategorii -->
    <div class="d-none d-xl-flex col-xl-2 d-flex justify-content-start align-items-start flex-wrap bg-white">
        <a href="{% url 'events:events_list' %}" class="w-100 text-center text-dark p-2">Powrót</a>
    </div>
{% endblock %}

{% block home_main %}
<!--Mapa wydarzenia -->
<div class="col-12 d-flex justify-content-start align-items-start flex-wrap">
    <div id="map" style="width: 100%; height: 600px;">
        {{ map_html|safe }}
    </div>
</div>
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/filters_events.js' %}"></script>
{% endblock %}

web/templates/events/includes/event_messages.html
{% for message in events_messages %}
    <div class="w-100 d-flex flex-wrap bg-white shadow-sm border-0 mb-3 p-3">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <h5>{{ message.event.name }}</h5>
            <p>Wysłano:&nbsp;{{ message.created_at }}</p>
        </div>
        <div class="col-12">
            <p>{{ message.message }}</p>
        </div>
    </div>
{% endfor %}

web/templates/events/includes/events_listing_map.html
{% extends "home/base.html" %}

{% load static %}


{% block home_main %}
<!--Mapa wydarzenia -->
<div class="col-12 d-flex justify-content-start align-items-start flex-wrap">
    <div id="map" style="width: 100%; height: 100vh;">
        {{ map_html|safe }}
    </div>
</div>
{% endblock %}

{% block home_js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/filters_events_map.js' %}"></script>
{% endblock %}

web/templates/events/includes/filters_event.html
<form id="filtersMenuDesktop" 
    method="get" 
    class="filters_form d-xl-flex col-12 justify-content-start align-items-start flex-column border-end p-0 m-0 bg-white"
    action="{% if request.resolver_match.url_name == 'events_list' %}{% url 'events:ajax_filter_events' %}{% else %}{% url 'events:ajax_filter_events_map' %}{% endif %}">
    
    <ul class="list-group col-12 mb-3 p-2">
        <p class="fw-bold col-12 mt-2">{{ filter_form.date_filter.label }}</p>
        <li class="list-group-item custom-list-group-item col-12">
            <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                <select 
                    class="form-select col-12 me-2" 
                    id="id_date_filter" 
                    name="{{ filter_form.date_filter.html_name }}">
                    {% for value, label in filter_form.date_filter.field.choices %}
                        <option value="{{ value }}" 
                            {% if value == request.session.event_filters.date_filter %} selected {% endif %}>
                            {{ label }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </li>

        <!-- Widoczna data, gdy użytkownik wybrał "Wybierz datę" -->
        <li 
            class="list-group-item custom-list-group-item col-12 mt-3" 
            id="date-display-wrapper" 
            {% if not request.session.event_filters.selected_date %}style="display: none;"{% endif %}>
            <div class="d-flex justify-content-between align-items-center">
                <p id="selected-date-text">
                    Wybrana data: <br><span class="fw-semibold">{{ request.session.event_filters.selected_date }}</span>
                </p>
                <button 
                    type="button" 
                    id="change-date-button" 
                    class="btn btn-secondary btn-sm ms-3">
                    Zmień
                </button>
            </div>
        </li>

        <li class="list-group-item custom-list-group-item col-12 mt-3" id="date-picker-wrapper" style="display: none;">
            <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                <input 
                    type="date" 
                    id="id_selected_date" 
                    name="{{ filter_form.selected_date.html_name }}" 
                    class="form-control col-12"
                    value="{% if request.session.event_filters.selected_date %}{{ request.session.event_filters.selected_date }}{% endif %}">
            </div>
        </li>
    </ul>

    <ul class="list-group col-12 mb-3 p-2">
        <p class="fw-bold col-12 mt-2">{{ filter_form.categories.label }}</p>
        {% for value, label in filter_form.categories.field.choices %}
            <li class="list-group-item custom-list-group-item col-12">
                <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                    <input 
                        class="form-check-input me-2 col-2" 
                        type="checkbox" 
                        id="id_categories_{{ value }}" 
                        name="{{ filter_form.categories.html_name }}" 
                        value="{{ value }}"
                        {% if value in request.session.event_filters.categories %} checked {% endif %}
                    >
                    <label 
                        class="form-check-label col-10" 
                        for="id_categories_{{ value }}">
                        {{ label }}
                    </label>
                </div>
            </li>
        {% endfor %}
    </ul>

    <ul class="list-group col-12 mb-3 p-2">
        <p class="fw-bold col-12 mt-2">{{ filter_form.location_type.label }}</p>
        {% for value, label in filter_form.location_type.field.choices %}
            <li class="list-group-item custom-list-group-item col-12">
                <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                    <input 
                        class="col-2 form-check-input me-2 location-checkbox" 
                        type="checkbox" 
                        id="id_location_type_{{ value }}" 
                        name="{{ filter_form.location_type.html_name }}" 
                        value="{{ value }}"
                        {% if value == request.session.event_filters.location_type %} checked {% endif %}
                    >
                    <label 
                        class="col-10 form-check-label" 
                        for="id_location_type_{{ value }}">
                        {{ label }}
                    </label>
                </div>
            </li>
        {% endfor %}
    </ul>
    
    <ul class="list-group col-12 mb-3 p-2">
        <p class="fw-bold col-12 mt-2">{{ filter_form.entry_type.label }}</p>
        {% for value, label in filter_form.entry_type.field.choices %}
            <li class="list-group-item custom-list-group-item col-12">
                <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                    <input 
                        class="col-2 form-check-input me-2 entry-checkbox" 
                        type="checkbox" 
                        id="id_entry_{{ value }}" 
                        name="{{ filter_form.entry_type.html_name }}" 
                        value="{{ value }}"
                        {% if value == request.session.event_filters.entry_type %} checked {% endif %}
                    >
                    <label 
                        class="col-10 form-check-label" 
                        for="id_entry_{{ value }}">
                        {{ label }}
                    </label>
                </div>
            </li>
        {% endfor %}
    </ul>
    
    <ul class="list-group col-12 mb-3 p-2">
        <p class="fw-bold col-12 mt-2">{{ filter_form.added_by.label }}</p>
        {% for value, label in filter_form.added_by.field.choices %}
            <li class="list-group-item custom-list-group-item col-12">
                <div class="form-check col-12 d-flex flex-wrap justify-content-start align-items-center">
                    <input 
                        class="col-2 form-check-input me-2 added-by-checkbox" 
                        type="checkbox" 
                        id="id_added_by_{{ value }}" 
                        name="{{ filter_form.added_by.html_name }}" 
                        value="{{ value }}"
                        {% if value == request.session.event_filters.added_by %} checked {% endif %}
                    >
                    <label 
                        class="col-10 form-check-label" 
                        for="id_added_by_{{ value }}">
                        {{ label }}
                    </label>
                </div>
            </li>
        {% endfor %}
    </ul>
</form>

web/templates/events/includes/popup_content.html
<div style="width: 300px;">
    {% if event.main_image %}
        <img src="{{ event.main_image.url }}" alt="{{ event.name }}" style="width: 100%; height: auto;"/>
    {% endif %}
    <a href="{% url 'events:event_details' slug=event.slug pk=event.id %}" target="_blank">
        <h4 class="mt-2">{{ event.name }}</h4>
    </a>
    <div class="col-12 col-xl-3 d-flex justify-content-end align-items-center">
        {% if event.event_type == 'one_day' %}
            <span>{{ event.one_day_date }}</span>
        {% elif event.event_type == 'is_multi_day' %}
            <span>{{ event.start_date }}&nbsp;-&nbsp;{{ event.end_date  }}</span>
        {% else %}
            <div class="event-days col-12 mt-2">
                {{ event.get_day_of_week_display }}
            </div>
        {% endif %}
    </div>
    <p>{{ event.address }}</p>
    <p>{{ event.description|truncatechars:100 }}</p>
</div>